name: Build Desktop App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install fastapi pexpect uvicorn pywebview pyinstaller

      - name: Install GTK dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-gi gir1.2-gtk-3.0 libgirepository1.0-dev libcairo2-dev

      - name: Install GTK backend for pywebview
        run: |
          pip install PyGObject

      - name: Install Qt backend for pywebview
        run: |
          pip install PyQt5

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --add-data "static:static" desktop.py --name proxmark3-hf-mfdes

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: proxmark3-hf-mfdes
          path: dist/proxmark3-hf-mfdes